export const siteConfig = {
  name: "Muhammad Ali Ghias",
  shortName: "MAG",
  title: "Muhammad Ali Ghias | Software Engineer & Graphic Designer",
  description:
    "Official portfolio of Muhammad Ali Ghias — also known as Ali Ghias and Ghias. Software Engineer, Graphic Designer, and Microsoft Learn Student Ambassador based in Peshawar, Pakistan.",
  url: "https://www.muhammadalighias.me",
  locale: "en_US",
  /** Full portrait used for WhatsApp / OG / Twitter / Google search previews */
  ogImage: "https://www.muhammadalighias.me/og-image.png",
  avatarImage: "https://www.muhammadalighias.me/og-image.png",
  email: "muhammadalighias@gmail.com",
  phone: "+92 326 5763041",
  location: {
    city: "Peshawar",
    region: "KPK",
    country: "Pakistan",
  },
  github: "https://github.com/ali-ghiax",
  linkedin: "https://www.linkedin.com/in/muhammad-ali-ghias/",
  instagram: "https://www.instagram.com/ali_ghiax/",
  tiktok: "https://www.tiktok.com/@ali_ghiax",
  whatsapp:
    "https://wa.me/923265763041?text=Assalamualaikum%20Ghias%2C%20I%20found%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project.",
  keywords: [
    "Muhammad Ali Ghias",
    "muhammad-ali-ghias",
    "Muhammad Ali Ghias portfolio",
    "Ali Ghias",
    "ali ghias",
    "Ali Ghias developer",
    "Ali Ghias designer",
    "MAG",
    "MAG portfolio",
    "Ghias",
    "ghias",
    "Ghias portfolio",
    "ali-ghiax",
    "Software Engineer",
    "Graphic Designer",
    "Web Developer Peshawar",
    "MLSA CUSIT",
    "Microsoft Learn Student Ambassador",
    "Freelance Graphic Designer Pakistan",
    "React Developer",
    "Next.js Developer",
    "CUSIT",
    "Peshawar",
  ],
} as const;

export const sitePages = [
  { path: "/", priority: 1, changeFrequency: "weekly" as const },
  { path: "/about", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/experience", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/projects", priority: 0.95, changeFrequency: "weekly" as const },
  { path: "/certifications", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/skills", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/honors", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/contact", priority: 0.85, changeFrequency: "monthly" as const },
] as const;
